name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # Install a specific Gradle version and DISABLE caching
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: "8.6"
          cache-disabled: true

      - name: Build Debug APK
        run: gradle :app:assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          name: Honeyword-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
