name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34"
          # Try preferred build-tools, then fallback
          (sdkmanager --install "build-tools;34.0.0") || sdkmanager --install "build-tools;33.0.2"
          # Create a Gradle wrapper pinned to 8.4 (works with AGP 8.2.2)
      - name: Create Gradle wrapper (8.4)
        run: gradle wrapper --gradle-version 8.4

      - name: Build Debug APK (verbose)
        run: ./gradlew :app:assembleDebug --stacktrace --info | tee build.log
        shell: bash

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
        
          name: build-log
          path: build.log

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Honeyword-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
