name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ clean-start ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34"
          for v in 34.0.2 34.0.1 34.0.0 33.0.2; do
            sdkmanager --install "build-tools;$v" && echo "Using build-tools $v" && break
          done

      - name: Ensure Gradle wrapper (8.6)
        run: |
          if [ ! -f ./gradlew ]; then gradle wrapper --gradle-version 8.6; fi
          chmod +x gradlew
          ./gradlew --version

      - name: Assemble Debug APK (verbose)
        run: ./gradlew clean :app:assembleDebug --stacktrace --info --no-daemon 2>&1 | tee build.log
        shell: bash

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
