name: Build APK (diagnostic)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34"
          for v in 34.0.2 34.0.1 34.0.0 33.0.2; do
            sdkmanager --install "build-tools;$v" && echo "Using build-tools $v" && break
          done

      - name: Ensure gradle.properties (safety)
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          cat gradle.properties

      - name: Create Gradle wrapper (8.6)
        run: gradle wrapper --gradle-version 8.6

      - name: Resource link only (capture real AAPT2 error)
        run: ./gradlew :app:processDebugResources --stacktrace --no-daemon 2>&1 | tee build.log
        shell: bash

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
