name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: android-actions/setup-android@v3

      - name: Install SDK components (resilient)
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platform-tools" "cmdline-tools;latest" "platforms;android-34"
          for v in 34.0.2 34.0.1 34.0.0 33.0.2; do
            if sdkmanager --install "build-tools;$v"; then
              echo "Using build-tools $v"
              break
            fi
          done

      - name: Create Gradle wrapper (8.6)
        run: gradle wrapper --gradle-version 8.6

      - name: Build Debug APK (verbose)
        run: ./gradlew clean :app:assembleDebug --stacktrace --info | tee build.log
        shell: bash

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

      - name: Upload APKs (any location)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/**/*.apk
            **/*.apk
          if-no-files-found: warn
