name: Build APK
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - uses: gradle/actions/setup-gradle@v3
      - name: Build Debug APK
        run: gradle :app:assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Honeyword-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
